name = "ABM"
uid = "8043c0e7-f9e7-483c-0006-a9ab1ec6445e"
version = 6
description = "This is ABM (Azraeel's Balance Mod) This mod is intended to address not just unit balance but address economic balance. The major changes are the rebalancing of Energy Economices by making Energy more needed throughout the game, also rebalancing T3 Air Phase, and more! (I'll Add Changelog later)"
author = "Azraeel and Others"
icon = "/mods/Azraeel's Balance Mod/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
